#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression --message="Stopping service..."
ynh_systemd_action --service_name=$app --action=stop

ynh_script_progression --message="Removing systemd service..."
ynh_remove_systemd_config

ynh_script_progression --message="Removing files..."
ynh_secure_remove --file="$install_dir"
ynh_secure_remove --file="$data_dir"

ynh_script_progression --message="Removing user..."
ynh_system_user_delete --username=$app

ynh_script_progression --message="Removal complete."